management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

dmz:
  url: https://dmz.credit-suisse.com
  polling: false

rocket:
  url: https://open.rocket.chat
  user-id: iBanKyDbcd7x3nWkv
  auth-token: gR33YJDTMSnLg2ObeJdX7950X8AL2JgO3aARNHUqIT8

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@triokluster-tk1kx.mongodb.net/test?retryWrites=true&w=majority
